channels:
- anaconda
- pytorch
- conda-forge
- menpo
dependencies:
- python>=3.7,<3.8
- pip>=21.0,<22
- pytorch==1.12.1
- torchvision==0.13.1
- torchaudio==0.12.1
- cudatoolkit=11.6
- nvidia-apex==0.1.0
- scikit-image
- opencv
- cupy
- pytorch-lightning
- pip:
  - matplotlib>=3.3,<3.4
  - psutil>=5.8,<5.9
  - tqdm>=4.59,<4.60
  - pandas>=1.1,<1.2
  - scipy>=1.5,<1.6
  - numpy>=1.10,<1.20
  - tensorboard
  - future==0.18.2
  - --find-links https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
  - kornia
  - hydra-core
  - wget
  - seaborn
  - easydict
  - torchpq
  - git+https://github.com/lucasb-eyer/pydensecrf.git
  - setuptools==59.5.0
  - pyDeprecate==0.3.1
name: stego
